// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHoP8QsCN--bvJlWE7RDc5qh8lVU_wZ5Q',
    appId: '1:657562697192:android:80ea68083821034a00f85d',
    messagingSenderId: '657562697192',
    projectId: 'eco-ride-07',
    databaseURL: 'https://eco-ride-07-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eco-ride-07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqAwGPgdw5-FgRuOKhLYHWmA3iwukpi7A',
    appId: '1:657562697192:ios:350d044a9442014000f85d',
    messagingSenderId: '657562697192',
    projectId: 'eco-ride-07',
    databaseURL: 'https://eco-ride-07-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eco-ride-07.firebasestorage.app',
    iosClientId: '657562697192-inf2h9o4j373rf08porfjgl3qcuk55tb.apps.googleusercontent.com',
    iosBundleId: 'com.ecoride.ecoRideMobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB90eAT7i-HvXXRyqGJIU4_87tsaLenxsw',
    appId: '1:657562697192:web:0236606067c0c14400f85d',
    messagingSenderId: '657562697192',
    projectId: 'eco-ride-07',
    authDomain: 'eco-ride-07.firebaseapp.com',
    databaseURL: 'https://eco-ride-07-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eco-ride-07.firebasestorage.app',
    measurementId: 'G-5PWWE96T5E',
  );

}